spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tutorials_tags
    password:
    username: root
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 1000
